language: java
sudo: false
jdk:
- oraclejdk8
matrix:
  include:
  - jdk: oraclejdk8
script: travis_wait 30 mvn verify org.pitest:pitest-maven:mutationCoverage
notifications:
  slack:
    secure: Vcrg6S2F40pTLir+D4eegQINQm0UKSRdwU5gzXwzfUX4pGLWPv1NzExZb6S8LXXTNU7j5Udop/XelgBps4iverYeDlEOSe+Abr8i7YTBvz1oyRzVj02HMtiVykJ76NbaVsjpdFXacW24FLlApbBjDvCp1E1xnvdVs4CH8qlY8IQE9vJW0YQNi0umOMVGyrQoIDbKha9NT/d+/HGkxSUB7X6t5G5ZAUoJryJQ9bvJrx9Vx0KQdKjYTCpLKzKbXKEv+hYsuUEozUXKwDZM+Xvuf2j0tSiRUqE1g550eoO/gUjfjza4vMG2LKX7B+IP29VNc8wDW3dt373hnk6qTeaBZOFjnf/XXB3vbQeFydFO2wmtF0XY2R2xqr2or+M71s1BjU+/AbbI5NEm5jBWy6x+P2Mb4NXbJ3wxVBH2vkdKJ2LIZL3xQCa86lLsdbdlItdY38ZSbLRTTlt+fatFErfeqj1LfOQFpwbQSyffB475m5WhOZw+iG8oiyuo7MoGoupmP7eQtJGO60mfEP7aYImmxHrX6wYtkyU55TNfYXx7plfpFVU6JUiDmbwqmWptywnY5YcXeIdvnRSfsl0YwpCbeCl+hi6fOV31vIwMhYTUVjA39SznO5vV34R2ep61pxv51lQyGxA4OyKyBGs1H6gOTSuPkwlr2l7H09FohahsFV4=
